### ISSUE TITLE
Hardware design questions

### ISSUE THREAD

**Issue by patfelst** [mike-rankin/ESP32_CoinCell_Color_TFT#1]
Hi this is a great project, thanks for sharing. I have a few questions about the h/w design:

1. Why did you change the USB-Serial chip to CP2104, as it is not recommended for new designs?
![image](https://user-images.githubusercontent.com/11342773/98050258-35f81f80-1e81-11eb-8db3-6eeee9a84a3c.png)

On the CP2102, the REGIN (pin 7) and VDD (pin 6) can also be connected to disable the onboard regulator. It still looks like you've been able to reduce the number of passives with the CP2104, e.g. no reset pullup.

2. Surprised how few high freq bypass caps (e.g. 100nF) you have (none!) for the ESP32? Did you determine they aren't needed through trial and error? You just have the single large 100uF cap.

3. Wondering how you can replace the inductor in the antenna matching circuit with a cap?

Thanks in advance!

**Comment by mike-rankin** [comment]
Older revisions used the CP2102 but it needed many more capacitors and resistors around it and is physically much larger. Had no idea that the 2102 is not recommended for new designs. Thanks for the tip!
On my next revision I'll add more decoupling capacitors around the CP2102 and will try and fit in more capacitors for the ESP32. Right now the board is so tiny and four layers that I lucked out. On larger four layer boards I have several 150uF electrolytic hanging off the pawer pins.
For the antenna it looks like capacitors of a small value in series look correct: https://dl.espressif.com/dl/schematics/esp32-pico-kit-v4_schematic.pdf and https://github.com/tinypico/tinypico-hardware/blob/master/TinyPICO%20Release%20P3/TinyPICO_Schematic.pdf

**Comment by patfelst** [comment]
Thanks for that. The CP2102 also comes in a QFN24 package which is pin compatible with the CP2104.

Thanks for the links, the matching network does indeed have a different topology than others I've seen. But I guess if all 3 matching components use the same 0402 (or 0603) footprint then you can choose whatever topology you want during assembly.

If you look at the PICO-D4 "module" schematic (i.e. inside the chip), it has a built-in matching network (see yellow circle below), and also bypass caps and an inductor noise filter L5 (see cyan circle below), so you probably don't need an antenna matching network, and is probably why you're getting away with no decoupling caps.
![image](https://user-images.githubusercontent.com/11342773/98063489-1a504180-1ea0-11eb-8cf0-f2c489f33620.png)

![image](https://user-images.githubusercontent.com/11342773/98064077-6059d500-1ea1-11eb-9a5a-5b37344fabfe.png)


Anyway all the best, great work once again.

**Comment by mike-rankin** [comment]
Thanks for the 24pin CP2102N tip. I've only used the 28pin version in the past and will order the 24pin version to see if it works well as a drop in sub. It's great that the ESP32 pico has taken car eof so many things internally. I'm working with the nRF52 now it is very unforgiving if you don't really know what you are doing.
